.segment "PROGRAM"

jmp _main
;
; File generated by cc65 v 2.18 - Git ece63f0
;
	.fopt		compiler,"cc65 v 2.18 - Git ece63f0"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_puts
	.export		_main

.segment	"RODATA"

.segment	"PROGRAM"
L0005:
	.byte	$48,$65,$6C,$6C,$6F,$20,$66,$72,$6F,$6D,$20,$43,$21,$0A,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"PROGRAM"

.proc	_main: near

.segment	"PROGRAM"

;
; puts("Hello from C!\n");
;
	lda     #<(L0005)
	ldx     #>(L0005)
	jsr     _puts
;
; }
;
	rts

.endproc

