[[ics]]
name = "SlowBus-AFT16V8B"
pins = 20
vcc = 3.3
vectors = [
    # __       _    ____
    # SR5432R  OV21ФWRRI

    # Reset
	"C10XXXXXXG1LZZZHHXXV",

    # Slow bus
    # Fast mode
	"C11XXXXXXG0HLLHXXXXV",
	"C11XXXXXXG0LLLLXXXXV",
    # Slow mode
	"C01XXXXXXG0LLLHXXXXV",
	"C01XXXXXXG0LLHLXXXXV",
	"C01XXXXXXG0LLHHXXXXV",
	"C01XXXXXXG0HHLLXXXXV",
	"C01XXXXXXG0HHLHXXXXV",
	"C01XXXXXXG0HHHLXXXXV",
	"C01XXXXXXG0HHHHXXXXV",
	"C01XXXXXXG0LLLLXXXXV",
    # Fast mode (again)
	"C11XXXXXXG0HLLHXXXXV",
	"C11XXXXXXG0LLLLXXXXV",

    # Read/write qualifier
    # /WD + /RD when Ф2=0
	"011XXXX0XG0LLLLHHXXV",
	"011XXXX1XG0LLLLHHXXV",
    # /WD + /RD when Ф2=1
	"C11XXXX0XG0HLLHLHXXV",
	"011XXXX1XG0HLLHHLXXV",
    # /WD + /RD when Ф2=0 (again)
	"C11XXXX1XG0LLLLHHXXV",

    # Address decoder
    # /RAM enable ($0000-$7FFF)
	"0110000XXG0XXXXXX11V",
	"0110001XXG0XXXXXX11V",
	"0110010XXG0XXXXXX11V",
	"0110011XXG0XXXXXX11V",
	"0110100XXG0XXXXXX11V",
	"0110101XXG0XXXXXX11V",
	"0110110XXG0XXXXXX11V",
	"0110111XXG0XXXXXX11V",
    # /ROM enable ($8000-$BFFF, 16K LOROM)
	"0111000XXG0XXXXXX01V",
	"0111001XXG0XXXXXX01V",
	"0111010XXG0XXXXXX01V",
	"0111011XXG0XXXXXX01V",
    # Unused ($C000-$CFFF)
	"0111100XXG0XXXXXX11V",
    # I/O ($D000-$DFFF)
	"0111101XXG0XXXXXX10V",
    # /ROM enable ($E000-$DFFF, 8K HIROM)
	"0111110XXG0XXXXXX01V",
	"0111111XXG0XXXXXX01V",
]
