[[ics]]
name = "SlowBus-GAL20V8"
pins = 24
vcc = 3.3
vectors = [
    #  __        _     ____
    #  SR5432R   O V21ФWRRI

    # Reset
	"CX10XXXXXXXG1XLZZZHHXXXV",

    # Slow bus
    # Fast mode
	"CX11XXXXXXXG0XHLLHXXXXXV",
	"CX11XXXXXXXG0XLLLLXXXXXV",
    # Slow mode
	"CX01XXXXXXXG0XLLLHXXXXXV",
	"CX01XXXXXXXG0XLLHLXXXXXV",
	"CX01XXXXXXXG0XLLHHXXXXXV",
	"CX01XXXXXXXG0XHHLLXXXXXV",
	"CX01XXXXXXXG0XHHLHXXXXXV",
	"CX01XXXXXXXG0XHHHLXXXXXV",
	"CX01XXXXXXXG0XHHHHXXXXXV",
	"CX01XXXXXXXG0XLLLLXXXXXV",
    # Fast mode (again)
	"CX11XXXXXXXG0XHLLHXXXXXV",
	"CX11XXXXXXXG0XLLLLXXXXXV",

    # Read/write qualifier
    # /WD + /RD when Ф2=0
	"0X11XXXX0XXG0XLLLLHHXXXV",
	"0X11XXXX1XXG0XLLLLHHXXXV",
    # /WD + /RD when Ф2=1
	"CX11XXXX0XXG0XHLLHLHXXXV",
	"0X11XXXX1XXG0XHLLHHLXXXV",
    # /WD + /RD when Ф2=0 (again)
	"CX11XXXX1XXG0XLLLLHHXXXV",

    # Address decoder
    # /RAM enable ($0000-$7FFF)
	"0X110000XXXG0XXXXXXX11XV",
	"0X110001XXXG0XXXXXXX11XV",
	"0X110010XXXG0XXXXXXX11XV",
	"0X110011XXXG0XXXXXXX11XV",
	"0X110100XXXG0XXXXXXX11XV",
	"0X110101XXXG0XXXXXXX11XV",
	"0X110110XXXG0XXXXXXX11XV",
	"0X110111XXXG0XXXXXXX11XV",
    # /ROM enable ($8000-$BFFF, 16K LOROM)
	"0X111000XXXG0XXXXXXX01XV",
	"0X111001XXXG0XXXXXXX01XV",
	"0X111010XXXG0XXXXXXX01XV",
	"0X111011XXXG0XXXXXXX01XV",
    # Unused ($C000-$CFFF)
	"0X111100XXXG0XXXXXXX11XV",
    # I/O ($D000-$DFFF)
	"0X111101XXXG0XXXXXXX10XV",
    # /ROM enable ($E000-$DFFF, 8K HIROM)
	"0X111110XXXG0XXXXXXX01XV",
	"0X111111XXXG0XXXXXXX01XV",
]
